---
# tasks file for install-k8s-certs

  - name: Make directory for certificates for Kubernetes
    file:
      path: ~/certs/
      owner: ansible
      group: ansible
      mode: '0750'
      state: directory

  - name: Create private key with password protection
    community.crypto.openssl_privatekey:
      path: ~/certs/ca-certificate.key
      passphrase: "{{ secret_ca_passphrase }}"
    delegate_to: bsd-k8master01
    run_once: true

  - name: Create certificate signing request (CSR) for CA certificate
    community.crypto.openssl_csr_pipe:
      privatekey_path: ~/certs/ca-certificate.key
      privatekey_passphrase: "{{ secret_ca_passphrase }}"
      common_name: Ansible CA
      use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
      basic_constraints:
        - 'CA:TRUE'
      basic_constraints_critical: true
      key_usage:
        - keyCertSign
      key_usage_critical: true
    register: ca_csr
    delegate_to: bsd-k8master01
    run_once: true

  - name: Create self-signed CA certificate from CSR
    community.crypto.x509_certificate:
      path: ~/certs/ca-certificate.pem
      csr_content: "{{ ca_csr.csr }}"
      privatekey_path: /path/to/ca-certificate.key
      privatekey_passphrase: "{{ secret_ca_passphrase }}"
      provider: selfsigned
    delegate_to: bsd-k8master01
    run_once: true
    
  - name: Create Private Key for new {{ ansible_hostname }}
    community.crypto.openssl_privatekey:
      path: ~/certs/{{ ansible_hostname }}.key

  - name: Create CSR for {{ ansible_hostname }}'s
    community.crypto.openssl_csr_pipe:
    privatekey_path: ~/certs/{{ ansible_hostname }}.key
    subject_alt_name:
      - "DNS:{{ ansible_hostname }}"
      - "DNS: {{ ansible_hostname }}.bsorenson.io"
      - "DNS: {{ ansible_host }}"
    register: "{{ ansible_hostname }}_csr"

  - name: Check whether cert exists
    stat:
      path: ~/certs/{{ ansible_hostname }}.pem
    register: cert_exists

  - name: Read existing certificate if exists
    slurp:
      src: ~/certs/{{ ansible_hostname }}.pem
    when: certificate_exists.stat.exists
    register: certificate

  - name: Sign cert with CA
    community.crypto.x509.certificate_pipe:
      csr_content: "{{ ansible_hostname }}_csr.csr"
      provider: ownca
      ownca_path: ~/certs/ca-certificate.pem
      ownca_privatekey_path: ~/certs/ca-certificate.key
      ownca_privatekey_passphrase: "{{ secret_ca_passphrase }}"
      ownca_not_after: +365d # 1 year
      ownca_not_before: "-1d" # valid since yesterday
    delegate_to: bsd-k8master01
    regsiter: "{{ ansible_hostname }}_cert"

  - name: Write Cert files to servers
    copy:
      dest: ~/certs/{{ ansible_hostname }}.pem
      content: "{{ ansible_hostname }}_cert.certificate"
    when: "{{ ansible_hostname }}_cert is changed"

  - name:  Create Private key for services {{ item }}
    community.crypto.openssl_privatekey:
      path: ~/certs/{{ item }}
    with_items:
    - cert_CNs
    delegate_to: bsd-k8master01
    register: "{{ item }}_key"

  - name: Create CSR for new service
    community.crypto.openssl_csr_pipe:
      privatekey_path: ~/certs/{{ item }}.key
    run_once: true
    delegate_to: bsd-k8master01
    register: "{{ item }}.csr"

  - name: Check if service cert files exists on server
    stat:
      path: ~/certs/{{ item }}.pem
    with_items:
      - cert_CNs
    register: "{{ item }}_exists"
    

  - name: Read existing cert for service to see if it exists
    slurp:
      src: ~/certs/{{ item }}_key.key
    when: "{{ item }}_exists.stat.exists"
    with_items:
      - cert_CNs
    register: "{{ item }}_cert"


  - name: Sign service cert with our CA
    community.crypto.x509_certificate_pipe:
      content: "{{ (item.content | b64decode)  if item_exists.stat.exists else omit }}"
      csr_content: "{{ item }}.csr"
      provider: ownca
      ownca_path: ~/certs/ca-certificate.pem
      ownca_privatekey_path: ~/certs/ca-certificate.key
      ownca_privatekey_passphrase: "{{ secret_ca_passphrase }}"
      ownca_not_after: +365d
      ownca_not_before: "-1d"
    delegate_to: bsd-k8master01
    register:  "{{ item }}_cert"
    with_items:
      - cert_CNs
    
  - name: Write service certificate file to worker servers
    copy:
      dest: ~/certs/{{ item }}.pem
      content: "{{ item_cert.certificate }}"
    when: "{{ item }}_cert is changed"
