all:
  children:
    vsphere:
      hosts:
        bzd-kubespray01:
           ansible_host: 10.0.30.164
        bzd-kubespray02:
          ansible_host: 10.0.30.166
        bzd-kubespray03:
          ansible_host: 10.0.30.165
        bzp1-ansible:
          ansible_host: 10.0.30.145
        unifi:
          ansible_host: 10.0.4.10
    azure:

