- name: Configure Unifi server
  hosts: network
  become: true
  gather_facts: true
  vars:
    ANSIBLE_USER: "{{ lookup('env', 'ANSIBLE_USER') }}"
    ANSIBLE_PASSWORD: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
    ansible_become_password: "{{ ANSIBLE_PASSWORD }}"
    large_client_header_buffers: "2 1k"
    client_max_body_size: "100K"
    client_body_timeout: 10
    client_header_timeout: 10
    strict_transport_security_max_age: 15768000 #max-age directive with 15768000 seconds (six months) or longer
    nginx_site_config_dir: /etc/nginx/sites-available/
    #Or ALL:!EXP:!NULL:!ADH:!LOW:!SSLv2:!SSLv3:!MD5:!RC4;
    ssl_ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384


    nginx_key: /etc/letsencrypt/live/unifi.bsorenson.io/privkey.pem
    nginx_cert: /etc/letsencrypt/live/unifi.bsorenson.io/fullchain.pem

    backendserver: http://localhost:8443
    backendserver_ssl: true

    access_log: /var/log/nginx/unifi.bsorenson.io.com.access.log
    error_log: /var/log/nginx/unifi.bsorenson.io.error.log warn

    domainName: unifi.bsorenson.io
  roles:
  - role: ansible-cis-nginx-hardening
    tags:
    - ever
    - harden-nginx
    - Configure-Infra
  - role: Configure-Ubiquiti
    tags:
    - never
    - Configure-Ubiquiti
    - Configure-Infra
