- name: Configuring Golden Image
  hosts: kubernetes
  connection: ssh
  become: true
  roles:
  - name: Install-Python
    tags:
    - Install-Python
    - ever
  - name: Install-SSH-Keys 
    tags:
    - Install-SSH-Keys
    - ever
  - name: Add-Sudoers
    tags:
    - ever
    - Add-Sudoers
  tasks:
  - name: Update Ubuntu
    apt:
      name: "*"
      state: latest


