- name: Configuring Golden Image
  hosts: all
  vars:
  roles:
  - name: Update all packages
    tags:
    - Update-CentOS
    - ever
  
  - name: Build Python
    tags:
    - Install-Python
    - ever
  - name: Create user
    tags:
    - Create-User
    - ever
  - name: Install authorized SSH keys 
    tags:
    - Install-SSH-Keys
  - name: Add Sudoers
    tags:
    - ever
    - Add-Sudoers